version: "3"

services:
  stardog:
    build: .
    environment:
      - STARDOG_SERVER_JAVA_ARGS=-Xmx8g -Xms8g -XX:MaxDirectMemorySize=12g
    ports:
      - 5820:5820
    volumes:
      - ./volumes/stardog:/var/opt/stardog

  studio:
    image: stardog/stardog-studio:current
    ports:
      - 8080:8080
